import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-6 p-4 border-b border-gray-200 dark:border-gray-700 mb-8">
          <a href="/login" className="hover:underline">
            Login
          </a>
          <a href="/home" className="hover:underline">
            Home
          </a>
          <a href="/forms" className="hover:underline">
            Forms
          </a>
        </nav>
        {children}
      </body>
    </html>
  );
}
